[package]
name = "ocipkg-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
cargo_metadata = "0.15.0"
clap = { version = "3.2.8", features = ["derive"] }
colored = "2.0.0"
env_logger = "0.9.0"
git2 = "0.14.4"
log = "0.4.17"
serde_json = "1.0.82"
url = "2.2.2"

[dependencies.ocipkg]
version = "0.2.0"
path = "../ocipkg"

[[bin]]
name = "ocipkg"

[[bin]]
name = "cargo-ocipkg"
