[package]
name = "ocipkg-cli"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
license = "MIT OR Apache-2.0"
version = "0.2.1"
edition = "2021"

description = "CLI for ocipkg"
documentation = "https://docs.rs/ocipkg-cli"
repository = "https://github.com/termoshtt/ocipkg"
readme = "../README.md"

[dependencies]
base64 = "0.13.0"
cargo_metadata = "0.15.0"
clap = { version = "3.2.8", features = ["derive"] }
colored = "2.0.0"
env_logger = "0.9.0"
git2 = "0.13.25"
log = "0.4.17"
serde_json = "1.0.82"
url = "2.2.2"

[dependencies.ocipkg]
version = "0.2.0"
path = "../ocipkg"

[[bin]]
name = "ocipkg"

[[bin]]
name = "cargo-ocipkg"
