[package]
name = "cync"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base16ct = { version = "0.1.1", features = ["alloc"] }
oci-spec = "0.5.6"
sha2 = "0.10.2"
structopt = "0.3.26"
tar = "0.4.38"
