[package]
name = "ocipkg"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
base16ct = { version = "0.1.1", features = ["alloc"] }
directories = "4.0.1"
flate2 = "1.0.24"
oci-spec = "0.5.6"
sha2 = "0.10.2"
structopt = "0.3.26"
tar = "0.4.38"
