[package]
name = "ocipkg"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
base16ct = { version = "0.1.1", features = ["alloc"] }
bytes = "1.1.0"
directories = "4.0.1"
env_logger = "0.9.0"
flate2 = "1.0.24"
lazy_static = "1.4.0"
log = "0.4.17"
regex = "1.5.6"
reqwest = { version = "0.11.11", features = ["json"] }
serde = "1.0.137"
sha2 = "0.10.2"
tar = "0.4.38"
tokio = { version = "1.19.2", features = ["rt", "rt-multi-thread", "macros"] }
url = "2.2.2"
cargo_metadata = "0.15.0"
uuid = { version = "1.1.2", features = ["v4"] }
clap = { version = "3.2.8", features = ["derive"] }
serde_json = "1.0.82"
git2 = "0.14.4"
thiserror = "1.0.31"
chrono = "0.4.19"
oci-spec = "0.5.7"
walkdir = "2.3.2"
