[package]
name = "ocipkg"
version = "0.3.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.70.0"
description = "OCI registry for package distribution"
documentation = "https://docs.rs/ocipkg"
repository = "https://github.com/termoshtt/ocipkg"
readme = "../README.md"

[dependencies]
base16ct = { version = "0.1.1", features = ["alloc"] }
base64 = "0.22.0"
chrono = "0.4.31"
directories = "5.0.1"
flate2 = "1.0.28"
lazy_static = "1.4.0"
log = "0.4.18"
oci-spec = "0.6.5"
regex = "1.7.3"
serde = "1.0.197"
serde_json = "1.0.115"
sha2 = "0.10.8"
tar = "0.4.40"
thiserror = "1.0.58"
toml = "0.5.11"
ureq = { version = "2.9.3", features = ["json"] }
url = "2.5.0"
uuid = { version = "1.5.0", features = ["v4"] }
walkdir = "2.5.0"

[dev-dependencies]
maplit = "1.0.2"
