[package]
name = "ocipkg-lib-example"
version = "0.1.0"
edition = "2021"

[package.metadata.ocipkg]
registry = "ghcr.io/termoshtt/ocipkg/rust-lib"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
