name: examples

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  rust-lib:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: --features=cli --path=. -f
    - name: Add path
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Build and publish a container with cargo-ocipkg
      run: |
        cd examples/rust-lib
        ocipkg login -u ${{ github.repository_owner }} -p ${{ github.token }} https://ghcr.io
        cargo ocipkg build
        cargo ocipkg publish

  rust-exe:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: --features=cli --path=. -f
    - name: Add path
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Build container of rust-lib example
      run: |
        cd examples/rust-lib
        cargo ocipkg build -t ghcr.io/termoshtt/ocipkg/rust-lib:latest
        ocipkg load $(find . -name "ocipkg_*.tar")

    - name: Build rust-exe example
      run: |
        cd examples/rust-exe
        cargo build
