name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  pages:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --no-deps --all-features
    - name: Deploy GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
        force_orphan: true
