name: Keep a Changelog

on:
  pull_request: {}

jobs:
  check-updated:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - run: bash -c "! git diff --exit-code origin/main... CHANGELOG.md"
